name: Run Shell Scripts

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Shell Environment
      run: |
        sudo apt-get update
        echo "Set up completed"
    
    - uses: browser-actions/setup-chrome@v1
    - run: chrome --version
     
    - name: Make Shell Script Executable
      run: |
        chmod +x ./Fireflink-Client.sh
        chmod +x ./Signin.sh

    - name: Install Client into machine
      run: |
        ./Fireflink-Client.sh
        
    - uses: GuillaumeFalourd/wait-sleep-action@v1
      with:
        time: '60s'
        
    - name: Signing in to Fireflink
      run: |
        ./Signin.sh ${{vars.USERNAME}} ${{vars.PASSWORD}}

    - uses: GuillaumeFalourd/wait-sleep-action@v1
      with:
        time: '1h' # for 1 hour
        

