name: Run Shell Scripts

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
   
    - name: Set up Shell Environment
      run: |
        sudo apt-get update
        echo "Set up completed"
     
    - name: Make Shell Script Executable
      run: |
        chmod +x ./Fireflink-Client.sh
        chmod +x ./Signin.sh

    - name: Run Shell Scripts
      run: |
        ./Fireflink-Client.sh
        
    - name: Run Shell Scripts
      run: |
        ./Signin.sh

