name: Run Shell Scripts

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Shell Environment
      run: |
        sudo apt-get update
        echo "Set up completed"

    - name: Run Shell Scripts
      run: |
        ./Fireflink-Client.sh
        ./Signin.sh

